[package]
name = "sqlparser"
version = "0.1.0"
authors = ["mitubaEX <g1344955@cse.kyoto-su.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
